version: "3"
services:
    web:
        build:
            context: ./
            dockerfile: ./Dockerfile
        ports:
            - 8082:80
            - 8083:443
        environment:
            #- ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=Password1234
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        volumes:
            - ~/.aspnet/https:/https:ro